- block:
    - name: Install haproxy on master nodes
      become: true
      when: inventory_hostname in groups['master_servers']
      ansible.builtin.yum:
        state: present
        name: 
          - haproxy-{{ haproxy_version }}

    - name: Stop haproxy service
      become: true
      when: inventory_hostname in groups['master_servers']
      service:
        name: haproxy
        state: stopped

    - name: Set setsebool -P haproxy_connect_any=1
      become: true
      when: inventory_hostname in groups['master_servers']
      command: setsebool -P haproxy_connect_any=1

    - name: Copying haproxy conf to all master servers
      become: true
      when: inventory_hostname in groups['master_servers']
      template:
        src: haproxy.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: "0644"

    - name: Force systemd to reload configs
      become: true
      when: inventory_hostname in groups['master_servers']
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart and enable haproxy and keepalived on master nodes
      become: true
      when: inventory_hostname in groups['master_servers']
      service:
        name: haproxy
        enabled: true
        state: restarted

    - name: Prevent haproxy and keepalived from being updated
      become: true
      when: inventory_hostname in groups['master_servers']
      community.general.yum_versionlock:
        state: present
        name:
        - haproxy
